[package]
name = "tokio_throughput"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strict-num = "0.2"
tokio = "1"
